dependencies:
  - name: builder
    version: <builder-tag>
    repository: https://charts.deis.cc/builder
  - name: slugbuilder
    version: <slugbuilder-tag>
    repository: https://charts.deis.cc/slugbuilder
  - name: dockerbuilder
    version: <dockerbuilder-tag>
    repository: https://charts.deis.cc/dockerbuilder
  - name: controller
    version: <controller-tag>
    repository: https://charts.deis.cc/controller
  - name: slugrunner
    version: <slugrunner-tag>
    repository: https://charts.deis.cc/slugrunner
  - name: database
    version: <database-tag>
    repository: https://charts.deis.cc/database
  - name: fluentd
    version: <fluentd-tag>
    repository: https://charts.deis.cc/fluentd
  - name: redis
    version: <redis-tag>
    repository: https://charts.deis.cc/redis
  - name: logger
    version: <logger-tag>
    repository: https://charts.deis.cc/logger
  - name: minio
    version: <minio-tag>
    repository: https://charts.deis.cc/minio
  - name: monitor
    version: <monitor-tag>
    repository: https://charts.deis.cc/monitor
  - name: nsqd
    version: <nsqd-tag>
    repository: https://charts.deis.cc/nsqd
  - name: registry
    version: <registry-tag>
    repository: https://charts.deis.cc/registry
  - name: registry-proxy
    version: <registry-proxy-tag>
    repository: https://charts.deis.cc/registry-proxy
  - name: registry-token-refresher
    version: <registry-token-refresher-tag>
    repository: https://charts.deis.cc/registry-token-refresher
  - name: router
    version: <router-tag>
    repository: https://charts.deis.cc/router
  - name: workflow-manager
    version: <workflow-manager-tag>
    repository: https://charts.deis.cc/workflow-manager
